// src/constants/subjects.js
export const SCHOOL_SUBJECTS = [
  "Mathematics",
  "English Language",
  "Physics",
  "Chemistry",
  "Biology",
  "Further Mathematics",
  "Economics",
  "Government",
  "Literature in English",
  "Geography",
  "Civic Education",
  "Computer Studies",
  "Agricultural Science",
  "Technical Drawing",
  "Fine Art",
  "Music",
  "Yoruba",
  "Igbo",
  "Hausa",
  "French",
  "Christian Religious Studies",
  "Islamic Religious Studies",
  "Physical & Health Education",
  "Home Economics",
  "Business Studies",
  "Social Studies",
  "Basic Science",
  "Basic Technology",
  "Quantitative Reasoning",
  "Verbal Reasoning",
  // Add more subjects specific to your school
];